name: hello_world

on:
  push:

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
      - id: s00
        run: echo "Current time in Github is $(date)"
      - id: s02
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: 'Moo moo cow'
          color: green
  